server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Intercept 404 errors and send them to the @redirect_root block
    error_page 404 = @redirect_root;

    location / {
        try_files $uri $uri/ =404;
    }

    location @redirect_root {
        return 302 /;
    }
}
