server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # Direct NGINX to use bundled 404.html for 404 errors
    error_page 404 /404.html;

    # Ensure the 404 page is treated as an internal redirection
    location = /404.html {
        internal;
    }
}
